// 1) CREARE UN OGGETTO CHE DESCRIVA UNO STUDENTE CON LE SEGUENTI PROPRIETA' : NOME, COGNOME ED ETA'.

var studente = {

    "nome": 'Riccardo',
    'cognome': 'Pinco',
    'eta': 23,
}

console.log(studente);




// 2) STAMPARE CON CICLO FOR TUTTE LE PROPRIETA' DELL'OGGETTO.

for (var key in studente){
    console.log(studente[key]); 
}




// 3) CREARE UN ARRAY DI OGGETTI DI STUDENTI.







// 4) CICLARE TUTTI GLI STUDENTI E STAMPARE PER OGNINO DI ESSI NOME E COGNOME.







// 5) DARE LA POSSIBILITA' ALL'UTENTE CON 3 PROMPT DI AGGIUNGERE UN NUOVO OGGETTO STUDENTE INSERENDO NELL'ORDINE NOME COGNOME E ETA'.